### ISSUE TITLE
Local Report Page example throws error

### ISSUE THREAD

**Issue by adwait-godbole** [bowtie-json-schema/bowtie#1010]
![Screenshot (76)](https://github.com/bowtie-json-schema/bowtie/assets/68469605/c44cbe5d-f588-463d-b7bd-e46c0f160cc6)

Perhaps there should be a better example over there which works

**Comment by Julian** [comment]
There's no issue there, the implementation fails one of the tests.

**Comment by adwait-godbole** [comment]
Yeah what I meant was perhaps we could've shown a simpler example there that does not throw error on CLI so it doesn't look like something went wrong while executing the command. But anyways ig this is also fine.

**Comment by Julian** [comment]
That would mean we show an example of where everything passes essentially, which would be showing a fairly boring report.

My intuition is that a new user simply needs to learn what they're looking at there.

**Comment by adwait-godbole** [comment]
Okay 👍
