### ISSUE TITLE
Add support for other JavaScript implementations

### ISSUE THREAD

**Issue by JeelRajodiya** [bowtie-json-schema/bowtie#1018]
I have noticed that bowtie.report site has reports for only two JavaScript implementations,  Would it be possible to add the reports of other implementations as well ?

I found [this](https://github.com/ebdrup/json-schema-benchmark?tab=readme-ov-file) report, but it is 4 years old and it does not have data on the latest draft 2020-12 

I have listed some of the few Javascript implementations below. 

- [x] [@exdous/schemasafe](https://www.npmjs.com/package/@exodus/schemasafe) 
- [x] [@cfworker/json-schema](https://www.npmjs.com/package/@cfworker/json-schema).

**Comment by Julian** [comment]
The first one there is also already supported by Bowtie, but yeah adding support for the others is certainly welcome.

**Comment by JeelRajodiya** [comment]
### The `jsonschema` we have on the site is for GO, Rust, and Python. not JavaScript. Am I missing anything? 

![image](https://github.com/bowtie-json-schema/bowtie/assets/63534268/88cb7800-24f0-4233-a037-ca2ff7a16a40)

**Comment by Julian** [comment]
Yes, you're missing that that validator (like most of those on that list) only supports old drafts of JSON Schema, so you need to look at a dialect it supports (or its page, [here](https://bowtie.report/#/implementations/js-jsonschema), or to see that it's present in [Bowtie's images](https://github.com/bowtie-json-schema/bowtie/tree/main/implementations/js-jsonschema).

**Comment by jdesrosiers** [comment]
Most, if not all, of those implementations have not been maintained in a very long time. None of them support recent versions. If you want to add more JavaScript implementations, start with [@exdous/schemasafe](https://www.npmjs.com/package/@exodus/schemasafe) and [@cfworker/json-schema](https://www.npmjs.com/package/@cfworker/json-schema). Those and the other two that are already represented are the only ones anyone should be seriously considering using.

**Comment by JeelRajodiya** [comment]
@Julian should I update the list and remove the unsupported ones; and add [@exdous/schemasafe](https://www.npmjs.com/package/@exodus/schemasafe) and [@cfworker/json-schema](https://www.npmjs.com/package/@cfworker/json-schema)

**Comment by Julian** [comment]
Sure!
