### ISSUE TITLE
Opening Embed Badges dropdown on Implementation Report View page is too much on the left side

### ISSUE THREAD

**Issue by adwait-godbole** [bowtie-json-schema/bowtie#1043]
https://github.com/bowtie-json-schema/bowtie/assets/68469605/4f29c216-d70f-4b64-bb1f-619530eaca3f

Perhaps we could center it a little bit or better we can try using [React Bootstrap's Modals](https://react-bootstrap.netlify.app/docs/components/modal/#live-demo) ig ? (just a suggestion, since it would look more user friendly to open a modal instead given that its a pretty huge component to show on a dropdown click)

**Comment by Julian** [comment]
I'm certainly open to improvements here, as what's there was essentially just to get this at minimally good enough to go out, but can you elaborate a bit? Specifically what's not user friendly? Usually I'd understand user friendliness to mean "a user who wants to use this functionality can't figure out how to do so". But you seem to mean something else, having to do with how large the component is. What's wrong with a large component?

**Comment by Julian** [comment]
Oh I see your video and the title rename now -- your viewport is at lower resolution than mine I think, I hadn't looked at it at that resolution -- I guess on lower resolutions we probably should pad less, but yeah whatever improvements are fine there certainly.

**Comment by adwait-godbole** [comment]
Yeah @Julian my local machine is at a resolution of 1920x1080

**Comment by adwait-godbole** [comment]
Fixed in #1066
