### ISSUE TITLE
Hamburger menu doesn't work on mobile phone

### ISSUE THREAD

**Issue by OptimumCode** [bowtie-json-schema/bowtie#1068]
Hi, I can't open the hamburger menu on mobile phone. I tried Chrome and Safari but it doesn't work in both browsers.
![image](https://github.com/bowtie-json-schema/bowtie/assets/23560203/b4e086cd-efd1-4356-be67-a3b9e8c41a52)

Sorry if this is a duplicate - I checked but didn't find the suitable issue

**Comment by sd1p** [comment]
Working on this issue.

**Comment by OptimumCode** [comment]
Thank you @sd1p. This functionality in newly published report works fine
