### ISSUE TITLE
Bowtie website suddenly works very slowly after a few clicks here and there

### ISSUE THREAD

**Issue by adwait-godbole** [bowtie-json-schema/bowtie#1074]
I am not sure if it's just my machine or my mobile (I tested on both) but whenever I tried toggling between the dark and light mode a few times on the initial load of the website it worked smoothly but later when I tried toggling again after clicking on a few `Details` buttons in the summary report (you can see in the video below clicking on them after toggling dark/light mode was also very laggy as the cursor was not changing to pointer for some time) and later closing the opened modal, after that the toggling of the modes suddenly became very slow and laggy in behaviour.

Also although the issue #1068 was fixed in PR #1070, the behaviour of opening the navbar has became very slow on mobile to the point it doesn't even open the navbar for me even after multiple clicks which might indicate that the issue still remains.

https://github.com/bowtie-json-schema/bowtie/assets/68469605/5b46e428-f893-4152-a71e-febc5e634634

My guess is some serious state changes or side effects are causing this behaviour. 

Needs to be taken a look at a high priority @Julian and let me know if it's just me or are you facing this problem as well.

**Comment by adwait-godbole** [comment]
If it's just me or my machine or mobile's problem then I apologize in advance :)

**Comment by JeelRajodiya** [comment]
> If it's just me or my machine or mobile's problem then I apologize in advance :)
Can confirm, It is slowing down in my machine as well!

**Comment by JeelRajodiya** [comment]
@Julian I wish to work on this issue.

**Comment by JeelRajodiya** [comment]
> Thanks @JeelRajodiya for confirming, can you also confirm on mobile once if the issue https://github.com/bowtie-json-schema/bowtie/issues/1068 was really fixed by PR https://github.com/bowtie-json-schema/bowtie/pull/1070 or not.

It is taking more then one clicks to open the menu. 
On the first click, it sets the button in focus (but does not open the menu) 
On the second click, the website starts lagging. If I click few more time, eventually the menu opens.

(I am opening the site on chrome in an android phone)

**Comment by adwait-godbole** [comment]
Thanks again for confirming! :)

**Comment by sd1p** [comment]
I noticed that there is an extra CSS property `collapse` which is causing the bug. After testing hamburger menu on my phone, now the it works smoothly. 

![image](https://github.com/bowtie-json-schema/bowtie/assets/43758514/9fd8c27b-4be3-4431-b8b8-a2e6124bf326)

**Comment by adwait-godbole** [comment]
Yeah idm @sd1p. I wasn’t planning on taking up this issue and ig @JeelRajodiya already showed interest so you can confirm with him.

**Comment by JeelRajodiya** [comment]
> @adwait-godbole @JeelRajodiya  Can I take on fixing the Hamburger Issue?

Sure! It would be great. 

Also, Issues #1073 and #1074 can be related to the hamburger issue as well.
(But I'm not sure)

**Comment by sd1p** [comment]
I found out that all the accordions in the landing page are rendering their content even before they are opened, each accordion contains syntax highlighted schema, which is causing the delay in Dark/Light Theme toggle.

**Comment by Julian** [comment]
Fixed in #1077 I believe.
