### ISSUE TITLE
Add runtime information to implementation harness' metadata

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#117]
E.g. node version, Python version, OS, etc.

Just to include a bit more specific info in case any platform-specific or runtime-specific issue ever comes up.

Make sure this also is added to the IO schema and also is returned by `bowtie info` (though as long as it goes in `implementation.metadata` it should do so automatically).

**Comment by AgniveshChaubey** [comment]
Does this issue refers to addition of **_platform_**, **_python_version_**, **_node_version_**, etc along with name, language, version,..... in io-schema.json file?

```
"platform": {
  "type": "string",
  "description": "Operating system the implementation is running on"
},
"python_version": {
  "type": "string",
  "description": "Version of Python used to run the implementation"
},
"node_version": {
  "type": "string",
  "description": "Version of Node.js used to run the implementation"
```

**Comment by AgniveshChaubey** [comment]
Hi @Julian, just a quick reminder that I raised a PR for this issue yesterday. Would appreciate if you could take a look. Thanks!
