### ISSUE TITLE
Add a fragment link for badge generation to the UI

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#1204]
We have a modal which shows badge information for an implementation, see e.g.:

https://bowtie.report/#/implementations/go-jsonschema

and click the Badges button.

But there is no way to link to the modal, as it has no fragment.

We should add one such that https://bowtie.report/#/implementations/go-jsonschema/badges jumps directly to the modal.

**Comment by adwait-godbole** [comment]
working on this!

**Comment by adwait-godbole** [comment]
@Julian should we also make it so that when the user clicks on "Badges" button the url also changes to https://bowtie.report/#/implementations/go-jsonschema/badges ?

**Comment by Julian** [comment]
Yeah that sounds nice too I think
