### ISSUE TITLE
Add `bowtie filter-implementations --direct` for filtering implementations with direct connectable functionality

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#1260]
Running `bowtie filter-implementations --direct` should output only those implementations which can run without the presence of podman/dockerd.

**Comment by adwait-godbole** [comment]
working on this side by side!

**Comment by Julian** [comment]
Right now there's just a dict (`bowtie._direct_connectables.IMPLEMENTATIONS`) so it should be somewhat easy I suspect, you just check that `ImplementationInfo.id()` is in there I think.

**Comment by adwait-godbole** [comment]
> Right now there's just a dict (bowtie._direct_connectables.IMPLEMENTATIONS)
 
 Can't seem to find any such `dict` in [here](https://github.com/bowtie-json-schema/bowtie/blob/main/bowtie/_direct_connectable.py)

**Comment by Julian** [comment]
https://github.com/bowtie-json-schema/bowtie/blob/main/bowtie/_direct_connectable.py#L184

**Comment by adwait-godbole** [comment]
Oops, right sorry! My fork's `main` branch wasn't up to date with Bowtie 😅. Nevermind.

**Comment by adwait-godbole** [comment]
@Julian what should be the behaviour if the user does `--supports-dialect` or `--language` or `--implementation` along with doing `--direct` ?

**Comment by Julian** [comment]
We apply all filters (i.e. the same as what we do now).

**Comment by adwait-godbole** [comment]
> We apply all filters (i.e. the same as what we do now).

@Julian sorry to ping yet again, but I've got one more query over here, let's say the user does something like `bowtie filter-implementations --direct --language python`, so now in this case what would happen is that as a first layer we would start containers for all implementations then it would filter the ones which have language as python in them and then finally perform a check if that filtered `ImplementationInfo.id()` existed in the `bowtie._direct_connectables.IMPLEMENTATIONS` or not and then output just `python-jsonschema` for example (as it is the only direct connectable for now).

**Comment by adwait-godbole** [comment]
But overall this process seems very counterintuitive, right ? Applying filters on getting to know something which never wanted to start containers in the first place ? I propose we should just have overall another CLI command for this, maybe `filter-direct-connectables` or something like that or somehow just not make `filter-implementations` to start any containers at all if `--direct` was present ? Am I making sense ?

**Comment by adwait-godbole** [comment]
I think I am definitely overthinking on this one (since we only just wanted to filter amongst implementations which had the direct connectable functionality) but yeah hearing the term "direct connectable" and "starting a container to know what it was" just made me think this way.
