### ISSUE TITLE
Schematize the `implementations/*/matrix_versions.json` file

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#1264]
We should add a simple (private) schema for the matrix_versions.json file we're going to be adding to implementation harness directories.

`bowtie/schemas` (our existing registry of files) seems like a fine enough physical place for it to live.

CC @adwait-godbole

**Comment by adwait-godbole** [comment]
Cool! I will do this but just to confirm this [matrix_versions.json](https://github.com/bowtie-json-schema/bowtie/blob/3732101c858f50802bf3e2a589fa06ab9da3b495/implementations/ruby-json_schemer/matrix_versions.json) file is good to proceed with right?

**Comment by adwait-godbole** [comment]
or any other `properties` to add in here ?

**Comment by Julian** [comment]
Yes I think the format is fine for now (eventually I want to probably consider putting implementation metadata entirely in a JSON file and then as part of that maybe we merge this into that, but for now I think just the array is fine)
