### ISSUE TITLE
Teach bowtie summary to show validation results

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#127]
Right now it only shows errors + failures (meaning deviations from expected results), but we should also probably give it a way to show valid/invalid for particular instances & schemas, particularly so that `bowtie validate` has a way to become "show me the results".

**Comment by Julian** [comment]
Great! So right now if you run something like:

```
bowtie suite -i js-hyperjump -i dotnet-jsonschema-net https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/main/tests/draft7/type.json | bowtie summary
```

that will run the official JSON Schema tests from [this test suite file](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/main/tests/draft7/type.json) against 2 implementations (a Javascript one and a .NET one), and then should show you some output like:

```
                          Bowtie                          
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┓
┃ Implementation             ┃ Skips ┃ Errors ┃ Failures ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━┩
│ hyperjump-jsv (javascript) │ 0     │ 0      │ 0        │
│ JsonSchema.Net (dotnet)    │ 0     │ 0      │ 0        │
└────────────────────────────┴───────┴────────┴──────────┘
                       80 tests ran                       
```

which essentially means 80 tests were run, and those two implementations passed all the tests (they didn't say an instance was invalid when it was expected to be valid or vice versa, and they didn't crash).

`bowtie summary` also works if you want to directly check a specific schema against an instance, so e.g.:

```
bowtie validate --implementation js-hyperjump --implementation dotnet-jsonschema-net <(printf '{"type": "integer"}') <(printf '["foo", 1]') | bowtie summary
```

that will validate the instance `["foo", 1]` against the schema `{"type": "integer"` using those two implementations and again you should see this output:

```
                          Bowtie                          
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┓
┃ Implementation             ┃ Skips ┃ Errors ┃ Failures ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━┩
│ hyperjump-jsv (javascript) │ 0     │ 0      │ 0        │
│ JsonSchema.Net (dotnet)    │ 0     │ 0      │ 0        │
└────────────────────────────┴───────┴────────┴──────────┘
```

That output means that neither of those implementations errored ("crashed") when given that input. But it *doesn't* tell you whether those implementations consider that instance valid or not (it is invalid of course, because it isn't an integer, it's an array).

So this ticket means to improve `bowtie summary` so that not only can it tell you when an implementation crashes or fails a test, but also can be told to tell you what implementations think of instances themselves (whether they're valid or invalid).

One way of implementing that is to have a command line flag which switches whether you see validation results (valid/invalid) or test results (expected valid and was valid or expected invalid and was invalid, or failure -- expected valid and was invalid or vice versa) -- perhaps if you run:

`bowtie summary --show failures`

you should see what we currently show, but if you run:

`bowtie summary --show validation`

you should instead see a table like:

```
                                               Bowtie                          

Schema: {"type": "integer"}
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Instance                   ┃ hyperjump-jsv (javascript) ┃ JsonSchema.Net (dotnet) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ ["foo", 1]                 │ invalid                    │ invalid                 │
└────────────────────────────┴────────────────────────────┴─────────────────────────┘

```

which now summarizes what each implementation thought about the instance.

(Important: We need something that handles both one instance+schema at a time, like the above example, but also the case like `bowtie suite` where we have *80* instances and schemas, so the table will grow).

Hopefully that helps understand what the idea of this ticket is (if not ask!)

There is a test here for `bowtie summary`: https://github.com/bowtie-json-schema/bowtie/blob/main/tests/test_integration.py#L463-L497 - a good thing to try is to try adding one for the new thing we want to do, which you can run using pytest (https://docs.pytest.org/en/7.2.x/)

You'll need to review the documentation for `rich` (which is a library for drawing things like the table above). Those are [here](https://rich.readthedocs.io/en/stable/tables.html).

And then the place in Bowtie that'll need modifying is [here](https://github.com/bowtie-json-schema/bowtie/blob/main/bowtie/_cli.py#L125) which is what defines the behavior of running `bowtie summary`. You'll want to have a look at [click's documentation](https://click.palletsprojects.com/en/8.1.x/) which is the library used to define the command line interface, as you'll need to add the `--show` command line option I mentioned.

Hope that helps, feel free to follow up!

**Comment by dante381** [comment]
Thank you @Julian . I will go through the documentations . I really appreciate you guiding me through this issue.

**Comment by dante381** [comment]
I made some basic changes so that it displays an output. Just to confirm i am going in the right direction.

`bowtie validate --implementation js-hyperjump --implementation dotnet-jsonschema-net <(printf '{"type": "string"}') <(printf '1') | bowtie summary --show validation`

![image](https://user-images.githubusercontent.com/36447410/224240089-1ce3002a-eec6-4523-a758-ffc7a062473a.png)

Added a Command Line Flag `--show -s` with choices as failures | validation,

![image](https://user-images.githubusercontent.com/36447410/224243483-a302b2f0-d3ff-44fd-a9b7-e5ef511befdb.png)

![image](https://user-images.githubusercontent.com/36447410/224243661-d44c7bdf-fc65-4d11-9149-9e990943deed.png)

Tested it with example you provided,

`bowtie validate --implementation js-hyperjump --implementation dotnet-jsonschema-net <(printf '{"type": "integer"}') <(printf '["foo", 1]') | bowtie summary`

Result:

![image](https://user-images.githubusercontent.com/36447410/224244187-7881f97a-115b-4889-b9a8-11d9fa156961.png)

**Comment by Julian** [comment]
Nice! That indeed looks like you're on the right track!

I think also it's worth converting the word `False` to `invalid`, as it's a bit clearer. But yeah seems you're on the right track!

**Comment by dante381** [comment]
Hi @Julian,
I am able to display multiple instances with multiple schemas in different tables. But few instances are displaying the opposite result rather than what is expected i.e first instance of the first 5 schemas are printing the negation of the result(if the result is true it is print false)

Could you help me with this? Shall i make a PR so that you can view the changes?

**Comment by Julian** [comment]
Done by in #163 and #201 with some further tweaking (and still more that we could do). Thanks a lot @dante381!
