### ISSUE TITLE
Publish a JSON File with all the implementations details suitable for consumption by json-schema.org

### ISSUE THREAD

**Issue by benjagm** [bowtie-json-schema/bowtie#1312]
Could it be possible to have a JSON file containing the details of all the implementations?

- Name
- Source
- Supported Dialects

We are building the[ new Tooling page for the JSON Schema website](https://github.com/json-schema-org/website/issues/160) and we plan to add a depth integration with Bowtie. The idea is to shaw the shields of the implementations if they are in Bowtie. 

**Our problem is we don't know the bowtie name of each implementation** and without it we can generate the shield urls. As of now the only shared value in both data sources is the repo url (source) so if you guys provide this new file we'll manage to build all the shield urls using the Bowtie name of each tool.

Thanks a lot!

**Comment by adwait-godbole** [comment]
@Julian how are we planning to provide this ? We already generate the `known_implementations.json` file during the hatch(ling) build process but as we discussed that time, we could possibly end up inputting much more information in that file rather than just the implementation names. Also by sheild urls we mean the badges right ? Like e.g. https://bowtie.report/#/implementations/rust-boon/badges ? or something else ?

**Comment by adwait-godbole** [comment]
We already have one published at https://bowtie.report/implementations.json, right ?

**Comment by adwait-godbole** [comment]
> though again, private to us

so how to resolve that?

**Comment by Julian** [comment]
I'm not sure I understand the question! As I say, the goal of this issue is to publish a similar file, which we'll consider public, and whose target audience is the json-schema.org site, but it's meant to be very similar to what you linked (albeit with the keys being source URLs it sounds like).

**Comment by adwait-godbole** [comment]
What is an appropriate public url for such a file then ?

**Comment by Julian** [comment]
Haven't thought too hard there yet but possibly something like https://bowtie.report/v1/json-schema-org/implementations

**Comment by benjagm** [comment]
Hi everyone! Is there any update on this? This is critical for us to provide a seamless integration from the JSON Schema tooling page to Bowtie.

**Comment by Julian** [comment]
@benjagm @DarhkVoyd with big thanks to @adwait-godbole this is live.

You can find the file at http://bowtie.report/api/v1/json-schema-org/implementations -- and a JSON Schema for it [here](https://github.com/bowtie-json-schema/bowtie/blob/main/bowtie/schemas/api/v1/json-schema-org/implementations.json)

We wouldn't make backwards incompatible changes to that without coordinating, it's meant for you/json-schema.org.

We're making one last tweak to the exact format (which we mention [here](https://github.com/bowtie-json-schema/bowtie/pull/1408#issuecomment-2274049100)) and should go out shortly, but you can already start playing with that data if need be!

Let us know if there's anything else that'd help!

**Comment by DarhkVoyd** [comment]
@Julian @adwait-godbole This looks great! Thanks so much—much appreciated.
