### ISSUE TITLE
Suggestion: Use Bowtie ID as Primary Key in API Response Instead of Source URI

### ISSUE THREAD

**Issue by DarhkVoyd** [bowtie-json-schema/bowtie#1570]
**Description**:  
Currently, the Bowtie API returns data using the `source URI` as the primary key in the response object. This causes issues when integrating with tools that have inconsistent source URIs between Bowtie and JSON Schema. 

For example, in the case of `cfworker/json-schema`, the Bowtie source URI is:
```
https://github.com/cfworker/cfworker
```
While the JSON Schema source URI is:
```
https://github.com/cfworker/cfworker/blob/main/packages/json-schema/README.md
```
This inconsistency in complex projects such as monorepos causes difficulties when trying to fetch Bowtie badge data, as it requires us to manually match the source URIs.

### Proposed Change:  
We propose updating the Bowtie API to use the Bowtie `ID` as the primary key instead of the `source URI`. This change would:

**Current API Example**:
```json
{
    "https://github.com/cfworker/cfworker": {
        "id": "js-json-schema",
        "dialects": [...],
        "badges_urls": {...}
    },
    ...
}
```

**Proposed API Structure**:
```json
{
    "js-json-schema": {
        "source": "https://github.com/cfworker/cfworker",
        "dialects": [...],
        "badges_urls": {...}
    },
    ...
}
```

This structure would use the Bowtie `ID` (e.g., `js-json-schema`) as the key, making it easier to fetch data without relying on the `source URI`. The `source URI` would still be included as a nested value for reference purposes.

### Implementation:
If this suggestion is accepted, I am willing to contribute to making the necessary updates to the API.

**Comment by Julian** [comment]
Hey!

The point of the current format was precisely because how are you going to know what ID bowtie uses for each implementation?

Isn't that even less trivial to know than e.g. doing a prefix match whenever the URLs don't exactly match?

**Comment by DarhkVoyd** [comment]
The issue we face is that source URIs between Bowtie and JSON Schema sometimes differ (e.g., monorepos like `@cfworker/json-schema`). JSON Schema uses exact nested URIs, while Bowtie uses the root repo. This mismatch breaks our badge integration, as the URIs don't align.

Regarding your suggestion on prefix matching, there are two challenges:
1. Since reports are fetched dynamically, prefix matching would require client-side iteration over all keys, which could hurt performance.
2. Monorepos often host multiple tools (e.g., validators, schema generators). Prefix matching could link to all tools in the repo, which is undesirable. Using Bowtie IDs ensures we only fetch data for the intended tool, without affecting siblings.

Our current data model already stores Bowtie IDs, which we use for the outlink button to reports without querying the API. About obtaining the Bowtie ID, we plan to create a periodic workflow to loop over all IDs and update our stored Bowtie identifiers by matching source URIs and manually handle tools with inconsistent URIs. Since we only use the API for badges (not outlink slugs), switching the API to use Bowtie IDs as keys would resolve these issues. 

Let me know what you think!

**Comment by Julian** [comment]
> Since reports are fetched dynamically, prefix matching would require client-side iteration over all keys, which could hurt performance.

It shouldn't -- you would *pop* all exact match URLs first when building your own mapping, and be left with a small number of non-overlapping URLs, and then you can prefix match only on that small list (e.g. 2 or 3 of them).

> Prefix matching could link to all tools in the repo, which is undesirable.

I don't follow this, it sounds like something you have to solve regardless, even if you're going to try to assume what Bowtie's IDs are. How do you know which tool `js-json-schema` maps to in the UI?

All in all I suspect this change makes things significantly harder for you on the UI side, but I'm happy to make it if you'd like!

**Comment by DarhkVoyd** [comment]
- Unlike with exact matches, where we can confirm a tool's status definitively, the prefix matching introduces ambiguity. For tools without an exact match, we cannot be sure whether there is no corresponding Bowtie entry or if it merely doesn’t match the prefix. This results in needing to compare each tool's source with every remaining entry in the bowtieReport, leading to many redundant checks. Tools that don't have any matches still end up being checked against all entries. I would prefer to avoid this all together on the client-side. 
- Instead we could handle this with a periodic workflow. The workflow could process the tools periodically, applying the exact and prefix matches, and then update the tools' Bowtie IDs in the tooling data.

Let me know what you think!

**Comment by DarhkVoyd** [comment]
Thanks for your suggestion! I got an idea from it, where we first look for an exact match with the Bowtie report, and if that’s not found, we match up to the root URL (e.g., https://<git-provider>.com/<org>/<project>). This approach keeps things simple. I’ve implemented this for now and will see how it works. Thanks again!
