### ISSUE TITLE
Generate a clearer error message when `bowtie summary` or `bowtie report` get piped no data

### ISSUE THREAD

**Issue by dante381** [bowtie-json-schema/bowtie#178]
Expected Outcome: 
To return implementation data along with the error count and the case and results of each schema.
Reproduce the Issue:
`bowtie validate -i lua-jsonschema <(printf '{}')  <(printf '12') | bowtie summary`
`bowtie suite -i lua-jsonschema https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/main/tests/draft2020-12/ | bowtie report`

**Comment by Julian** [comment]
I renamed the issue here to be I think more like what we were talking about for this. Can you add the command that demonstrates the issue to the description? Thanks for filing!
