### ISSUE TITLE
Add --format json to bowtie info

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#188]
Like `bowtie summary`, `bowtie info` could benefit from a `--format json` option to make its output more easily machine-processable.

**Comment by dante381** [comment]
Hey @Julian ,
Currently `bowtie info` displays the implementation info using formatting. So this has to be replaced with `json.dumps`?

**Comment by Julian** [comment]
Hey @dante381 -- not replaced, added. If you try ` bowtie validate -i rust-boon <(printf '{"type": "integer"}') <(printf 12) <(printf '"37"') 2>/dev/null | bowtie summary` you'll see some prettified output, but if you add ` bowtie validate -i rust-boon <(printf '{"type": "integer"}') <(printf 12) <(printf '"37"') 2>/dev/null | bowtie summary --format json` you'll see structured JSON output. This is asking to add the same thing to `bowtie info` -- so if you run it with no arguments you should see the exact same thing as today, but if you add `--format json` you'd get the `json.dumps` version.
