### ISSUE TITLE
Images are not being rebuilt on release (or at all)

### ISSUE THREAD

**Issue by santhosh-tekuri** [bowtie-json-schema/bowtie#206]
see https://github.com/bowtie-json-schema/bowtie/actions/runs/4615138350

in which go-jsonschema is updated from 5.2.0 to 5.3.0.

but it did not build the images.yml

because of that the latest report still shows go-jsonschema 5.2.0

**Comment by Julian** [comment]
This is sort of "on purpose" at least in the sense that building images is currently "manual" only when I push a new release. We can change that though if we'd like (somehow decide when to release, e.g. every time a PR is merged perhaps), and then once we do so make that new way automatically apply to dependabot PRs.

**Comment by santhosh-tekuri** [comment]
my question is who you push manual release, then it did not build go-jsonschema. since because of recent changes to images.yml, it skips the image build

**Comment by Julian** [comment]
I should say there's a second "manual" step there too, which is the report doesn't automatically run on new releases either, so really if we want to fully automate things:

* automatically release a new version on some cadence when PRs are merged
* automatically trigger running a new report when new versions are released (keeping in mind we need to delay doing so a few minutes to ensure we don't pick up the old cached version in CI)
* automatically push the new version to Homebrew (https://github.com/bowtie-json-schema/homebrew-tap) which currently is done via a cron job that opens a PR (but needs manually merging)

I'm definitely OK with automating more of that, mostly what's there was 1) easy and 2) left me time to see how well it worked before automating more.

**Comment by Julian** [comment]
> my question is when you push manual release, then it did not build go-jsonschema. since because of recent changes to images.yml, it skips the image build

Oh I see. That sounds like a bug related to your path filter change. https://github.com/bowtie-json-schema/bowtie/actions/runs/4620283147 is the run that should have rebuilt it, but it looks like that run built no images.

**Comment by Julian** [comment]
I'm OK with making that be done as part of the PR, but yeah this worked previously, so definitely we should fix it one way or the other (either by making it happen as part of the PR, or by ignoring the filter logic during a release).
