### ISSUE TITLE
Add implementer documentation on badges

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#211]
We now generate at least 1 kind of badge! Hooray. (See #55)

We should add documentation for implementers showing them how to include badges in their own documentation.

See e.g. @santhosh-tekuri's https://github.com/santhosh-tekuri/boon#library-features README for an example.

#248 is a partial blocker here, as noted by Santhosh.

**Comment by santhosh-tekuri** [comment]
we should decide on badges path before working on docs;

you suggested some path changes: `badges/LANG-IMPLNAME/passing/Draft_XXX.json`

**Comment by Julian** [comment]
Agree (on both parts of that yeah)

**Comment by Julian** [comment]
We actually render this in the UI now, which is likely even better than it being in the docs. Let's call this closed, we'll maintain that badges modal going forward as we add any additional badges.
