### ISSUE TITLE
Add the networknt implementation - Java

### ISSUE THREAD

**Issue by Relequestual** [bowtie-json-schema/bowtie#303]
Previously, the networknt Java implementation reported that it supported 2019-09 and 2020-12, however the support is so weak that the support indicator on the official website listing was [removed](https://github.com/json-schema-org/json-schema-org.github.io/pull/525)!

While the implementation provides its own compliance report, it would be nice if it could be added here.

Logging an issue as requested.

**Comment by Julian** [comment]
We have at least one more thing to do here, namely the harness doesn't yet support registries apparently (thanks @harrel56 for pointing that out).
