### ISSUE TITLE
Missing dependency trogon when installing via Homebrew.

### ISSUE THREAD

**Issue by egekorkan** [bowtie-json-schema/bowtie#313]
I have installed bowtie over homebrew and when I tried to run it for the first time, it complained that there is no module named trogon. After installing it via pip, bowtie worked. Weird enough, it is actually in the dependencies at https://github.com/bowtie-json-schema/bowtie/blob/main/pyproject.toml#L57

**Comment by Julian** [comment]
Oh yes indeed thanks, I need to rerun something there.

**Comment by Julian** [comment]
Should be fixed now!
