### ISSUE TITLE
Implementations disappearing and reappearing from the live report

### ISSUE THREAD

**Issue by jdesrosiers** [bowtie-json-schema/bowtie#411]
It was pointed out to me today that the Hyperjump implementation isn't showing up on the bowtie report for 2020-12. It's there for all the other versions I support. The runner hasn't changed and still includes the 2020-12 dialect.

Any idea what happened?

**Comment by Julian** [comment]
For some reason runners in GitHub actions seem to be running out of disk space while generating reports (even though they're not very large??) which I think seems to be causing some instability...

Going to have a look, there are other implementations missing as well...

**Comment by Julian** [comment]
E.g. just now rerunning the report, Hyperjump is back, but 2 other implementations which were there disappear.... Still investigating.
