### ISSUE TITLE
Summary table border missing for answer unsuccessful column

### ISSUE THREAD

**Issue by Relequestual** [bowtie-json-schema/bowtie#418]
![Screenshot 2023-08-24 at 12 45 31](https://github.com/bowtie-json-schema/bowtie/assets/731158/c024648f-dfd2-40f0-9c37-ec4ac201e649)

It looks like this is something to do with positioning of the element using CSS.

For showing additional content on hover, should be able to use Bootstrap's [Popovers](https://getbootstrap.com/docs/5.3/components/popovers/#custom-container) feature with a custom container. It can be set to active on hover in addition to click. Suggests retain click for accessibility reasons.

**Comment by Relequestual** [comment]
I can't self assign, but feel free to assign me and/or ping me when I'm back from vacation.

**Comment by Julian** [comment]
Nice thanks! IIRC the crazy underline also had something to do with me trying to delineate *vertically* between tests and cases, but it's pretty ugly as is. Definitely happy if you tweak it!

**Comment by Julian** [comment]
Looks like we fixed this at some point? Here I see:

![Screenshot 2023-12-26 at 3 12 37 PM](https://github.com/bowtie-json-schema/bowtie/assets/329822/800464a8-c0cf-4042-8ecc-d86d8e4f9e8a)

Speak up if this still looks wrong but gonna close assuming it indeed is ok now.
