### ISSUE TITLE
The Java implementation(s) container images are huge

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#462]
Here's all of the current implementation images, sorted by size:

```
ghcr.io/bowtie-json-schema/lua-jsonschema                    latest         ada98b1dee70  38 hours ago  12.5 MB
ghcr.io/bowtie-json-schema/rust-boon                         latest         537e5358b2e8  38 hours ago  15.5 MB
ghcr.io/bowtie-json-schema/cpp-valijson                      latest         c933b4a17f90  38 hours ago  19.6 MB
ghcr.io/bowtie-json-schema/rust-jsonschema                   latest         e8826839973f  37 hours ago  21.2 MB
ghcr.io/bowtie-json-schema/go-jsonschema                     latest         2c54a892a7bb  38 hours ago  21.4 MB
ghcr.io/bowtie-json-schema/go-gojsonschema                   latest         9d4d4cf81827  38 hours ago  27.1 MB
ghcr.io/bowtie-json-schema/python-fastjsonschema             latest         e9885b29f040  38 hours ago  72.1 MB
ghcr.io/bowtie-json-schema/python-jschon                     latest         e651d5bc9169  38 hours ago  72.8 MB
ghcr.io/bowtie-json-schema/php-opis-json-schema              latest         37832c88e85e  38 hours ago  76.6 MB
ghcr.io/bowtie-json-schema/python-jsonschema                 latest         986e8813992c  38 hours ago  81.3 MB
ghcr.io/bowtie-json-schema/ruby-json_schemer                 latest         e5e850d96c76  38 hours ago  89.8 MB
ghcr.io/bowtie-json-schema/dotnet-jsonschema-net             latest         82dbabb4ba9d  38 hours ago  95.8 MB
ghcr.io/bowtie-json-schema/js-ajv                            latest         c73ebaf87d90  38 hours ago  189 MB
ghcr.io/bowtie-json-schema/js-hyperjump                      latest         4c5168da242d  38 hours ago  190 MB
ghcr.io/bowtie-json-schema/ts-vscode-json-languageservice    latest         9d17bdbe8dd5  38 hours ago  197 MB
ghcr.io/bowtie-json-schema/clojure-json-schema               latest         0b9aa8704bdc  38 hours ago  220 MB
ghcr.io/bowtie-json-schema/kotlin-kmp-json-schema-validator  latest         9e110e4ad454  38 hours ago  694 MB
ghcr.io/bowtie-json-schema/java-json-schema                  latest         e7faefb3c575  38 hours ago  716 MB
ghcr.io/bowtie-json-schema/java-json-schema-validator        latest         ebcda7fb387e  38 hours ago  716 MB
ghcr.io/bowtie-json-schema/java-openapiprocessor             latest         f1fe5d5c63da  28 hours ago  723 MB
```

Note that the JVM images are orders of magnitude larger than they should be / other images (even the JS ones are large!)

This is due to the images not using an alpine-based base image but...

Those are missing from Gradle, see the just-filed keeganwitt/docker-gradle#258.

Hopefully that gets fixed upstream.
In the meanwhile, or probably either way even, we could likely be making use of multi-step images to build the JARs separately and then run without Gradle installed. I believe there's a sample of such a thing [here in the CodeFresh docs](https://codefresh.io/docs/docs/example-catalog/ci-examples/gradle/).

We also likely should standardize the base image used. 2 images currently are based on JVM 11, and 2 on JVM 17, where likely all 4 could be based on the latter, if not newer (it seems 17 is the newest long term release of the JVM, so perhaps staying there is fine).

@relequestual also reminded us that there are other JVMs we might be interested in (e.g. OpenJDK) if for whatever reason using images using them turns out to be useful.

Help wanted from anyone with a JVM background if I don't get to it first.

**Comment by harrel56** [comment]
I'm gonna look into it if you haven't started yet. Never heard about "multi-stage builds" - but it looks like it's exactly what is needed here :)

**Comment by Julian** [comment]
I have not! But great!
