### ISSUE TITLE
Run harnesses without network access

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#49]

**Comment by lud** [comment]
Hello,

My implementation is supposed to fetch the `https://json-schema.org/draft/2020-12/schema` meta on first run. What should I do to allow the network to run?

**Comment by Julian** [comment]
It's generally recommended (by the spec team) that you be shipping copies of the metaschema.

If you don't though that's #703 which isn't yet implemented unfortunately but could be worked on!

**Comment by lud** [comment]
What I did is to warm up the cache during `docker build`, it seems to work fine.

I guess I'll have to include the metaschemas in my library at some point anyway.
