### ISSUE TITLE
Show the combined errors+failures number in reports

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#53]
This is really the total number of "incorrect" tests run by an implementation regardless of whether they fail or blow up. Right now we show these numbers separately.

**Comment by aku1310** [comment]
Hi @Julian,

I have set up the repo on my system, and going through the code base and documentation. I would like to work on this issue. Is there anything that I should keep in mind as I go through the codebase to resolve this issue? I am also new to this so any guidance would be appreciated.

If possible, can this issue be assigned to me so I can start working on resolving this?

**Comment by Julian** [comment]
Hi there -- great! Super appreciated -- I'm just thinking out loud on a design, but I think for this one a nice thing would maybe be instead of the 3 columns (skipped, failed, errored) to have just 2, skipped and unsuccessful (which should be failed + errored) -- and then to make it so that if you mouse over the number for unsuccessful to get a tooltip which shows the 2 numbers separately (failed and errored) and which also explains what those 2 categories mean -- failed means an implementation didn't crash but got the wrong answer, and errored means it crashed completely when trying to calculate an answer (which it should not).

Does that help? Let me know if you have any further questions.

**Comment by aku1310** [comment]
Thank you @Julian, this surely helps! I will get right into it and see how to make it work.

**Comment by aku1310** [comment]
Hi @Julian, I have made changes in the _cli.py, _report.py, and report.html.j2 files to show the failed and errored as unsuccessful by creating unsuccessful attribute in the _report.py and also added the necessary functions but when running the test on my local system, no changes are being shown in the report created. I feel that has to do with how I'm using the command from [here](https://bowtie-json-schema.readthedocs.io/en/latest/cli/#running-test-suite-tests-from-local-checkouts).

`bowtie suite $(find full/path/to/bowtie/implementations/ -mindepth 1 -maxdepth 1 -type d | sed 's/.*\/implementations\//-i /') full/path/to/JSON-Schema-Test-Suite/tests/draft7/type.json | bowtie report` 

![image](https://user-images.githubusercontent.com/72210364/224478156-8eb7aad4-e494-45e4-b856-a96e5288a392.png)

Could you please point me in the right direction as to what I might be doing wrong and how to go about it?

**Comment by Julian** [comment]
Hi there! I'll try to provide some more specific hints if you're still stuck after the weekend on Monday, but I don't think you should need to touch anything *except* `report.html.j2` -- which is a [jinja template](https://jinja.palletsprojects.com/en/3.1.x/) that renders the UI. But all the data you need *should* already be getting passed to it -- this is strictly a cosmetic change where in the Jinja template instead of showing separate columns, you can now *add* the `failed + errors` numbers to each other in each row in order to calculate what to show. No need to change anything upstream I don't think.

**Comment by aku1310** [comment]
Hi, thanks for pointing that out, I have followed up on your suggestion and `report.html.j2` is the only file that I've made changes to now. But the issue that I am facing is still not resolved. 

The expected result is still not visible on the generated report when I run the following command: 
`$ bowtie suite $(find E:/Coding/WebDeb/GSoC/Bowtie/bowtie/implementations/ -mindepth 1 -maxdepth 1 -type d | sed 's/.*\/implementations\//-i /') https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/main/tests/draft7/type.json | bowtie report`  as suggested [here](https://bowtie-json-schema.readthedocs.io/en/latest/cli/#running-test-suite-tests-from-local-checkouts) for local checkout. 

I will keep working on this for now, and hope to resolve it soon. Thank you for the suggestions!

**Comment by Julian** [comment]
Hi @aku1310 -- can you perhaps share a PR with your changes? If you've modified `report.html.j2` you should certainly see that affect new reports you generate but I'd have to see what you've changed to give further advice.

**Comment by Julian** [comment]
Ah! One other thing that occurs to me which seems like I didn't document well -- for Python packages, if you have a local checkout, you should run `pip install -e your/bowtie/checkout` if you want to see changes as you edit your checkout, rather than simply `pip install bowtie-json-schema`!

The `-e` option is the needed one.

Let me know if that helps! I should add it to a new section on contributing to the project.

**Comment by aku1310** [comment]
What should I put in `your/bowtie/checkout` as I am unable to find any directory or dependency named `bowtie/checkout`?

And yes, I will create the PR by today itself.

**Comment by Julian** [comment]
That meant "wherever you cloned bowtie to"!

**Comment by aku1310** [comment]
Using `pipx install -e your/bowtie/checkout` worked, I can now see my local changes in the generated report!

Also, is the styling restricted to only Bootstrap or can we use inline styling/different CSS file as well?

**Comment by Julian** [comment]
Great! And I'm perfectly fine with you using other styling!

**Comment by Julian** [comment]
Fixed by #166, thanks @aku1310!
