### ISSUE TITLE
Show "Average" compliance numbers in the report

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#54]
(Via @handrews in https://json-schema.slack.com/archives/C8CQ81GKF/p1667586349121349)

> hmmm... an "average" row in addition to the total would provide a sort of generalized state of the implementation landscape for a draft.  Not pushing for it, just a thought.

**Comment by Swarnendu0123** [comment]
> (Via @handrews in https://json-schema.slack.com/archives/C8CQ81GKF/p1667586349121349)
> 
> > hmmm... an "average" row in addition to the total would provide a sort of generalized state of the implementation landscape for a draft.  Not pushing for it, just a thought.

Can you explain to me a little bit more. Maybe I can give it a try.

**Comment by Julian** [comment]
This one needs more thinking to be worked on. It's about how to communicate the average level of passing tests across implementations, but I don't just want to do that via a number, because that number isn't very meaningful because the denominator isn't very meaningful (number of tests in the test suite). Almost certainly this depends on #157 which is why I removed the good first issue label.
