### ISSUE TITLE
Highlight the selected test case

### ISSUE THREAD

**Issue by gregsdennis** [bowtie-json-schema/bowtie#543]
When a test case has been clicked, the associated instance is populated into the top grid.  However, there should be some visual indication as to which test case is active.

![image](https://github.com/bowtie-json-schema/bowtie/assets/2676804/fc883d63-3207-44ee-a1b7-f69e4f4b9820)

In the screenshot, it's impossible to tell which case is shown in the "instance" column.

**Comment by Julian** [comment]
(Definitely seems like a good idea to me!)

**Comment by sudo-jarvis** [comment]
Hi @gregsdennis, @Julian 
I have implemented the enhancement and have created a PR for the same, kindly check.
