### ISSUE TITLE
Add bowtie suite --latest-supported

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#56]
Running it should execute the test suite against the latest supported JSON Schema dialect for (each) given implementation.

**Comment by vaibhav-1508** [comment]
Hey @Julian! I would like to work on this issue. I've gone through the documentation and have setup bowtie CLI on my system. Can you please guide me how to contribute?

**Comment by Julian** [comment]
Hi @vaibhav-1508 thanks for the offer!

This one might be deceptively difficult, but if you're looking for a challenge it'd definitely be appreciated!

What this ticket is asking is that right now, if you run something like:

```
⊙  bowtie suite -i clojure-json-schema -i cpp-valijson https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/main/tests/draft2020-12 | bowtie report                                                                                julian@Postmac
/opt/homebrew/Cellar/bowtie/0.72.2/libexec/lib/python3.11/site-packages/click/types.py:82: ResourceWarning: unclosed <ssl.SSLSocket fd=6, family=2, type=1, proto=0, laddr=('10.254.6.90', 64527), raddr=('140.82.113.5', 443)>
  return self.convert(value, param, ctx)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/opt/homebrew/Cellar/bowtie/0.72.2/libexec/lib/python3.11/site-packages/click/types.py:82: ResourceWarning: unclosed <ssl.SSLSocket fd=7, family=2, type=1, proto=0, laddr=('10.254.6.90', 64528), raddr=('140.82.113.10', 443)>
  return self.convert(value, param, ctx)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2023-03-13 10:11.27 [info     ] Will speak                     dialect=https://json-schema.org/draft/2020-12/schema
2023-03-13 10:11.27 [warning  ] Unsupported dialect, skipping implementation. [ghcr.io/bowtie-json-schema/cpp-valijson] dialect=https://json-schema.org/draft/2020-12/schema
2023-03-13 10:11.28 [warning  ] Unsupported dialect, skipping implementation. [ghcr.io/bowtie-json-schema/clojure-json-schema] dialect=https://json-schema.org/draft/2020-12/schema
2023-03-13 10:11.28 [error    ] No implementations started successfully!
```

you see those messages saying "Unsupported dialect, skipping implementation." -- because those implementations don't support the 2020-12 version of JSON Schema.

This ticket is asking to add a `--latest-supported` flag to the command line which runs whatever dialect is the latest one supported by an implementation.

So instead be able to write:

```
bowtie suite -i clojure-json-schema -i cpp-valijson --latest-supported
```

and that should run the tests from whatever the latest supported version of JSON Schema is for those two implementations (`clojure-json-schema` and `cpp-valijson`).

Note two things:

* I probably shouldn't have to specify a path to tests (in my first example that was https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/main/tests/draft2020-12) because now the `--latest-supported` option is what's going to decide which version is the one that's run
* If the implementations provided don't all support the same version we should probably just raise an error (e.g. imagine one implementation supports draft 7 as the latest, and the other draft 2019-09, then we should just error), because we don't yet support outputting reports with different versions of JSON Schema in them.

As I say though, this ticket can be slightly tricky! If you care to play around with it feel free to ask questions. But don't worry if you get stuck, if so we can find something a bit easier to get your feet wet.

Thanks!

**Comment by vaibhav-1508** [comment]
Thank you @Julian 
I'm working on the issue. I'll let you know if I run into any problem👾

**Comment by adwait-godbole** [comment]
Hey Julian can we accept --latest-supported as a bool  😅 ? Or do you expect it to be handled some other way ?

**Comment by Julian** [comment]
If you mean what the `click` `type` of that argument would be? That's a very very minor part of this issue, though yes we should do that as a callable, same as in your other ticket.

But good for you to focus on one thing at once, especially for a hard one. Work through the other ticket before starting on another.

**Comment by adwait-godbole** [comment]
Okay @Julian noted. I will finish the other ones first.

**Comment by adwait-godbole** [comment]
Now that we have #996 this becomes a lot easier, if we get `—latest-supported` then we can use the `-l` flag on `bowtie filter-dialects` to get the latest supported dialect for the implementations. But just like I mentioned in #24 , if we are already starting the implementations during filtration then no need of starting them up again :). Likely having PR #994 would help.

**Comment by adwait-godbole** [comment]
#996 makes this easier, if we get `—latest-supported` then we can use the `-l` flag on `bowtie filter-dialects` to get the latest supported dialect for the implementations. But just like I mentioned in #24 , if we are already starting the implementations during filtration then no need of starting them up again :). Likely having PR #994 would help. So, I would like to fix this one as well once we find a solution for #24.

**Comment by Julian** [comment]
There's actually something slightly tricky about this one -- the UI is almost certainly not ready to cope with a report that contains multiple different dialects in it. Nothing we currently run generates one, so even though the protocol was written with this in mind, we don't do it yet anywhere. I think that's probably the first thing to work out -- confirm that the local report page can cope with such a report, and then slightly tweak it because it would nowhere show the dialect right now.

But I agree that the actual CLI side is reasonably straightforward now.

**Comment by adwait-godbole** [comment]
> If the implementations provided don't all support the same version we should probably just raise an error

Also @Julian you had mentioned this earlier in the above comments, so there certainly won’t be a case where we have multiple dialects in the report right ?

**Comment by Julian** [comment]
> Why are we thinking from a UI viewpoint here though ? Where are we planning to show it in the UI exactly ? 

Usually when you generate the report there's 2 places to "do stuff" with it. You either pass it to `bowtie summary` or  you upload it to the local report page in the UI.

So those are the places I'm thinking about as where someone would take a report generated in this way.

> Also @Julian you had mentioned this earlier in the above comments, so there certainly won’t be a case where we have multiple dialects in the report right ? since we just raise an error.

We should think about that again basically, I'm not sure how useful it'll be if we only support cases where they have the same latest dialect. Actually I guess I'm not sure how useful this feature is entirely at this point, now that we have `bowtie filter-implementations`... we might even want to close it! I have to think a bit, but yeah feel free to chime in with thoughts.

**Comment by adwait-godbole** [comment]
Yeah, ig will have to think more on this one!
