### ISSUE TITLE
Bowtie website is broken

### ISSUE THREAD

**Issue by jdesrosiers** [bowtie-json-schema/bowtie#620]
Reporting in case it hasn't been noticed yet.

![image](https://github.com/bowtie-json-schema/bowtie/assets/716571/693a9898-a99a-4c29-bde3-74a9fcb496f6)

**Comment by Julian** [comment]
Huh, thanks... weird, will have a look, I assume the data generated from last night is wrong somehow.

**Comment by Julian** [comment]
Seems to be only the 2020-12 page somehow, as the [2019](https://bowtie.report/#/dialects/draft2019-09) and other filters on the 2020-12 report (like [just Java](https://bowtie.report/#/dialects/draft2020-12?language=java)) seem to work.

Still investigating.

**Comment by Julian** [comment]
Fixed for now, though will have to make this a bit more reliable. Thanks for letting me know.
