### ISSUE TITLE
Draft2019-09 report is incomplete 

### ISSUE THREAD

**Issue by harrel56** [bowtie-json-schema/bowtie#655]
https://bowtie.report/draft2019-09.json
https://bowtie.report/#/dialects/draft2019-09

This report is missing majority of test cases - other drafts seem fine

**Comment by Julian** [comment]
Whee, I fixed a similar issue yesterday, basically there's some error hardening missing (what's happening was the PHP implementation is sending invalid JSON in some cases, and Bowtie has a double bug where it's not catching that and then also not exiting saying it only ran a partial report).

The same is happening here (PHP sending invalid JSON), will see where else we're missing the error handling...

Thanks.

**Comment by Julian** [comment]
OK the 2 bugs should be fixed by 38c25b94e1722b8df0af6ba566d7c5e5ba16a93a (in bowtie) and 920bf366871a539d2fa0caa92cd70c6a0dec3e20 (in the PHP harness).

Will wait to close this until the report is rebuilt.

**Comment by Julian** [comment]
Now rebuilt at https://bowtie.report/#/dialects/draft2019-09 -- thanks again.
