### ISSUE TITLE
tutorial wording

### ISSUE THREAD

**Issue by karenetheridge** [bowtie-json-schema/bowtie#675]
In https://docs.bowtie.report/en/stable/implementers/

> so start requests will have two parameters:
> ...
> The harness is expected to respond with:

I think you mean "the harness is expected to respond with data that validates against this schema:" ?

**Comment by karenetheridge** [comment]
Also, it would be helpful to publish these schemas somewhere where they can be referenced, rather than having to hunt for them in the tutorial page (these all seem to be schema exerpts, not complete schemas in themselves, so the reader has to infer what they should look like).

**Comment by Julian** [comment]
> Also, it would be helpful to publish these schemas somewhere where they can be referenced,

This is #21 essentially (PRs of course always welcome).
