### ISSUE TITLE
Populate the GitPod MOTD with some simple Bowtie documentation

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#695]
It would probably be useful to have the [MOTD](https://www.networkworld.com/article/964193/how-to-use-the-motd-file-to-get-linux-users-to-pay-attention.html) in our new [Gitpod support](https://github.com/bowtie-json-schema/bowtie/blob/main/.gitpod.Dockerfile) show some example commands for using Bowtie.

Probably mirroring the ones from [the top of the CLI docs](https://docs.bowtie.report/en/stable/cli/) is a good start.

**Comment by sudo-jarvis** [comment]
Hi @Julian, I was trying to add the bowtie cli documentation to the MOTD for the gitpod workspace, however it seems that by default the motd file of gitpod has some content:

Welcome to Gitpod: Always ready to code. Try the following commands to get started:

        gp tasks list         List all your defined tasks in .gitpod.yml
        gp tasks attach       Attach your terminal to a workspace task

        gp ports list         Lists workspace ports and their states
        gp stop               Stop current workspace
        gp help               To learn about the gp CLI commands

For more information, see the Gitpod documentation: https://gitpod.io/docs

**Comment by sudo-jarvis** [comment]
I think the content can be the same as what is shown on running bowtie --help with an added examples section maybe

> I think the main important bit to start is just defining the contents of the message

**Comment by Julian** [comment]
That sounds pretty reasonable!
