### ISSUE TITLE
Automate updating implementation versions in harnesses

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#77]
This should possibly be easier than it sounds to automatically keep containers up to date -- most languages will likely have dependabot support for sending automated PRs to update lockfiles. If we set that up, we already would rebuild the image appropriately.

**Comment by jdesrosiers** [comment]
How does the dependabot work exactly? Will it update minor versions, or just patch versions? Anyone using semver would probably want it to update patch and minor versions, but not major versions.

**Comment by Julian** [comment]
> Will it update minor versions, or just patch versions? 

I left it at the default for now, but it's configurable, see the [update types option here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore) -- I figure we can tweak it however we'd like if it gets either too aggressive updating or not noisy enough?

**Comment by jdesrosiers** [comment]
Sounds good. I'll keep an eye on what it does next time I have an update for my library and look into tweaking behaviors if necessary.
