### ISSUE TITLE
Add `--format markdown` to commands

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#831]
It's useful to have a way to generate markdown-formatted output from e.g. `bowtie summary` for interoperability with other human-reader-targeted tooling.

If we had that, we could pipe that markdown to e.g. [GitHub Actions step summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) so that we see summary output when regenerating reports for the website.

We should add this for any command with `--format json` and `--format pretty` options. The desired output should match `--format pretty` as closely as possible, but with markdown-compatible syntax, leaving rendering up to the markdown engine.

We should also use an existing library to generate the markdown (I forget if rich can do this or if it can only *render* markdown, probably the latter, so we should pick an existing library capable of emitting markdown).

**Comment by sudo-jarvis** [comment]
@Julian , I was looking onto this, markdown doesnt seem to support showing nested tables as we use in `bowtie summary`, so some other way needs to be figured out to show the same data, it wouldnt be exactly like `--format pretty`

**Comment by Julian** [comment]
Ah -- indeed, that's a good point.

Maybe a good first step then is to only do this for `--show failures`, where there's no nested table.

And then we'd think of what to do for cases where we have to flatten the table for markdown...

**Comment by sudo-jarvis** [comment]
Hi @Julian 
I have implemented this and have created a PR for the same, kindly check.
