### ISSUE TITLE
Auto scroll to the instance when some test is clicked

### ISSUE THREAD

**Issue by sudo-jarvis** [bowtie-json-schema/bowtie#846]
When a test case has been clicked, the associated instance is populated into the top grid. However, in the case when a lot of test cases exist, one has to manually scroll up to the grid to view the populated instance. Ideally, after clicking the test case, it should automatically scroll up.

**On clicking:**
<img width="1710" alt="Screenshot 2024-02-10 at 4 30 34 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/75855708/f1937342-25c1-4bd4-bb98-02c53005adef">

**After Scrolling manually:**
<img width="1710" alt="Screenshot 2024-02-10 at 4 30 46 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/75855708/fee9fdad-d3e3-4100-977b-2880212cb2e2">

**Comment by sudo-jarvis** [comment]
Hi @Julian , I have identified a potential issue. If it seems valid to you, please assign it to me.

**Comment by Julian** [comment]
Seems reasonable!
