### ISSUE TITLE
 Syntax highlight schemas + instances in the terminal

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#863]
`rich` has support for syntax highlighting, so we should possibly make use of it in order to highlight schemas + instances in the terminal.

Doing this though probably would benefit from writing a Pygments highlighter that understands JSON Schema dialects -- something that likely is a good idea anyhow -- so this is probably the first step here.

**Comment by sudo-jarvis** [comment]
Ig the `rich` library that we already use itself supports syntax highlighting, so cant we just use rich instead of textual ?

**Comment by Julian** [comment]
That was just a typo (fixed), I meant rich.

The point is yes it supports highlighting but it won't do anything hugely useful really given it only understands JSON, not anything specific to JSON Schema.

**Comment by sudo-jarvis** [comment]
@Julian , so basically we need to write a custom highlighter for JSON schema that would support highlighting in a way similar to this ?

<img width="850" alt="Screenshot 2024-02-26 at 10 33 45 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/75855708/855bf89d-5b8a-4f38-ba04-8a8fdd15997c">

I dont know if its possible but it would be great if we are able to use the same highlighter on the frontend as well to highlight the instances and schemas.

**Comment by Julian** [comment]
Exactly yeah.

> I dont know if its possible but it would be great if we are able to use the same highlighter on the frontend as well to highlight the instances and schemas.

Sometimes it is. In the "modern world" there are a few different formats for doing highlighting. tree-sitter is the most powerful/recent (and probably not what we need for either frontend nor backend here) -- pygments is what the backend uses and has its own format for defining them, and the frontend probably uses or should/can use highlight.js -- and the two of those have somewhat close formats, so sometimes you can generate one from the other, or else share the definitions pretty closely.

**Comment by sudo-jarvis** [comment]
Ig for rich a custom highlighter can be made using rich itself: https://rich.readthedocs.io/en/stable/highlighting.html#custom-highlighters

**Comment by Julian** [comment]
It's [Syntax](https://rich.readthedocs.io/en/stable/reference/syntax.html#rich.syntax.Syntax) that's the relevant kind of highlighter in this case I think (which does appear to use pygments).

**Comment by sudo-jarvis** [comment]
Got it, so basically need to write a custom lexer for json schema.

**Comment by Julian** [comment]
Yeah, I think so (or one on top of the JSON lexer).

**Comment by sudo-jarvis** [comment]
I'll work on it, please assign it to me

**Comment by sudo-jarvis** [comment]
@Julian, I've made a basic Python program to create a custom lexer with all the keywords from https://www.learnjsonschema.com/2020-12/. Here's how it looks:

Rich automatically highlighted the code once the custom lexer was used:

```
custom_lexer = JSONSchemaLexer()

syntax = Syntax(code, lexer=custom_lexer, background_color="default", word_wrap=True)

console.print(syntax)
```

If this looks good to you, I'm ready to move forward and add it to the main code. Let me know if you have any suggestions or thoughts.

Result:
<img width="1369" alt="Screenshot 2024-02-27 at 5 36 54 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/75855708/74d1628c-0fa4-427e-ad9d-95ca842a1f2a">

**Comment by Julian** [comment]
Very nice! That looks great. Well done.

Let's even put that in its own package! I've created you a repo here -- https://github.com/python-jsonschema/jsonschema-lexer.

We can publish that and then add it as a dependency (but then others can use it as well, or we could upstream it to Pygments even).

**Comment by jdesrosiers** [comment]
I've done something similar for the language server. There are a few gotchas that someone relatively new to JSON Schema might miss. I'll post a few things to look out for in the new repo.
