### ISSUE TITLE
Hide the details button on reports when there are no failures

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#867]
On dialect pages we show details buttons next to implementations:

![Screenshot 2024-02-13 at 10 38 37 AM](https://github.com/bowtie-json-schema/bowtie/assets/329822/02dd78e9-bf1b-43d8-92e9-1357c244283a)

The modals these open are intended to show information about unsuccessful tests.

It's confusing however that for any passing implementation (all 0's) the modal shows a blank page.

We should likely not show the button at all for any implementation where it would be empty.

**Comment by sudo-jarvis** [comment]
Hi @Julian , solved this in #869.
