### ISSUE TITLE
Create a link to Bowtie reports inside the docs

### ISSUE THREAD

**Issue by benjagm** [bowtie-json-schema/bowtie#868]
I have been reading the Bowtie docs main page and it is focused on running Bowtie which is great, however I think it would be great to add a small section to talk about bowtie reports and navigate to them.

**Comment by Julian** [comment]
Yes! Definitely seems reasonable. Do you have a suggestion for where you think it goes? I guess a link on the homepage and then maybe some separate page with more information?

**Comment by benjagm** [comment]
I think with a brief section in the landing page may be ok for now.
