### ISSUE TITLE
Make the entire implementation name element clickable in dialect reports

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#870]
We show lists of implementations on dialect pages (including the homepage one of course).

![Screenshot 2024-02-13 at 11 52 20](https://github.com/bowtie-json-schema/bowtie/assets/329822/28b1a626-e083-428f-9031-8ae0014d66bd)

In that list, clicking the name links (in blue obviously) takes you to the implementation-specific page.

But we may as well make the entire element there clickable (and do the same thing) rather than just the text -- essentially making the name column be like a list of buttons which take you to the implementation page.

That makes them easier to click on, which is a good thing in this case since there's no real other logical reason someone would click on that spot on the page other than wanting to go to the implementation page.

**Comment by Julian** [comment]
@sudo-jarvis try to remember to include `Closes: #PRNUMBER` in your commit messages / PR description. I keep trying to remember to manually close yours but it's easier when it happens automatically :) And thanks again of course.

**Comment by sudo-jarvis** [comment]
Sorry for the inconvenience, will keep this in mind from next time onwards.
