### ISSUE TITLE
Rows without details buttons are not the same height as others on the UI report

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#873]
After #869 we now have rows in the table which are different heights than others:

![Screenshot 2024-02-13 at 2 05 35 PM](https://github.com/bowtie-json-schema/bowtie/assets/329822/cf414fcf-b4bb-4d49-b886-ea3cfbe460c6)

which is visually inconsistent.

We should make the row height the same even if the button isn't present.

The text is also not vertically centered in rows *with* the button, so we should fix that as well.

**Comment by XDreamist** [comment]
I might be able to help you with this problem.
