### ISSUE TITLE
Support attaching to a running implementation harness rather than starting one

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#874]
It would be nice to be able to attach to an externally managed harness container rather than having Bowtie start and stop them.

This would be useful for #35 or generally for performance-related use cases, as it makes it slightly easier to ignore time spent starting containers.

Also relates to #19 in that generalizing here will help that and/or rely on it.

**Comment by sudo-jarvis** [comment]
@Julian , wanted some clarification regarding this wrt #35. What does `attach to an externally managed harness container` mean here exactly? At any point bowtie itself would need to start the container right ? How else can the container be started on its own.

**Comment by Julian** [comment]
> At any point bowtie itself would need to start the container right ? How else can the container be started on its own.

Not necessarily! E.g. someone may directly run `podman run some/harness` / `docker run some/harness`!

But yes Bowtie could also offer commands to start (and then leave running) harnesses.

**Comment by sudo-jarvis** [comment]
@Julian, I am planning to pick this up in the community bonding period itself, because as mentioned by you it would be helpful for performance related usecases.

**Comment by Julian** [comment]
Great! Let's chat this week about it then, I have an idea for what to do such that the solution is general enough to also not get in the way of #19
