### ISSUE TITLE
Update the GitHub Actions documentation to show how to use Bowtie with GITHUB_STEP_SUMMARY

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#884]
#839 added a `--format markdown` output format to output markdown.

We should add a note on the [GitHub action documentation page](https://docs.bowtie.report/en/stable/github-actions/) which shows how to use this flag to e.g. output validation results for a schema + instance as part of a workflow run.

**Comment by sudo-jarvis** [comment]
@Julian, please assign this to me
