### ISSUE TITLE
Use the Schema/Instance Widget in Implementation Details Modals

### ISSUE THREAD

**Issue by Siddharth-Singh-2004** [bowtie-json-schema/bowtie#907]
Refactor schema, instance component (currently on the accordion) and have it work when called from accordion or implementation details modal.

This arises as an outcome of addressing issue #871.

Resue this part:
<img width="1246" alt="Screenshot 2024-02-20 at 10 18 22 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/112953828/41e16f37-1d20-4fbe-bc72-f04d349e351a">

Show in these two places:

1. Cases Accordion on home page showing Schema and Instance:
<img width="1271" alt="Screenshot 2024-02-20 at 10 20 47 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/112953828/c96eb74a-c3e3-4804-a050-eb7855b4a96f">

2. Implementation Details Modal showing Schema and Instance:

<img width="1943" alt="Screenshot 2024-02-20 at 10 22 34 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/112953828/868e1d76-ec33-45c7-988d-a22c592e4b86">

**Comment by Siddharth-Singh-2004** [comment]
I am working on refactoring the schema and instance component.

**Comment by Siddharth-Singh-2004** [comment]
Here is a view after incorporating Schema/Instance Widget in implementation Details Modal:

<img width="1690" alt="Screenshot 2024-02-21 at 1 05 02 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/112953828/034c83c1-e4bd-4bb9-8ed7-e9597b64238f">

**Comment by Julian** [comment]
Looks reasonable!

**Comment by Siddharth-Singh-2004** [comment]
Code changes to reuse schema-instance widget from Cases Accordion in Details Modal merged with pull request #905. Addresses part 3 of #871.
