### ISSUE TITLE
Running `bowtie info` pulls multiple Docker images with different tags for a single implementation along with the "latest" tag

### ISSUE THREAD

**Issue by adwait-godbole** [bowtie-json-schema/bowtie#918]
![Screenshot (49)](https://github.com/bowtie-json-schema/bowtie/assets/68469605/9735e6b4-84a9-4b7f-a7f7-b5c4e4c599ec)

**Comment by Julian** [comment]
Yup, this is the root cause of the GH Actions disk space issue :)

Good eye.

**Comment by adwait-godbole** [comment]
Oh! What a coincidence! I was so annoyed because of this. I was constantly deleting the irrelevant ones by hand :(

**Comment by adwait-godbole** [comment]
Lucky my Gitpod credits ran out today that it forced my hand setting up everything locally on machine :)

**Comment by Julian** [comment]
This is fixed in the latest release thankfully!

(Closing, but tell me if you don't see the same.)
