### ISSUE TITLE
Fix the mobile UI to not horizontally scroll / bleed elements out of their containers

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#925]
The below screenshots are on Firefox Android, but I suspect reproduce across mobile browsers:

![Screenshot_20240223-091343](https://github.com/bowtie-json-schema/bowtie/assets/329822/9924ee72-7f09-4f3a-8e76-5ac3c22bf26f)
![Screenshot_20240223-091352](https://github.com/bowtie-json-schema/bowtie/assets/329822/b8e1b04a-77ed-4b4d-a673-9311d1ed20ee)

We should fix our components to render correctly on mobile browsers without leaking from their containers or horizontally scrolling the page.

**Comment by skushagra9** [comment]
can I work on this

**Comment by Julian** [comment]
Great, go for it!
