### ISSUE TITLE
Reduce the amount of padding in the UI on mobile

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#930]
The mobile UI has too much padding:

![Screenshot 2024-02-24 at 9 45 20 AM](https://github.com/bowtie-json-schema/bowtie/assets/329822/6d03c310-0dba-4e88-b622-3da010877c3c)

We should make that look more normal, where there's only a small bit of space.

**Comment by nomandhoni-cs** [comment]
Hey @Julian  I am, already doing some testing with this, how much padding will look better in mobile devices.
Also I am trying to test different style of navbar in mobile devices.

**Comment by harrel56** [comment]
I noticed that implementation page (e.g. https://bowtie.report/#/implementations/ruby-json_schemer) still overflows on mobile - maybe it's worth to take care of it in scope of this issue too

**Comment by nomandhoni-cs** [comment]
@harrel56 sure, I will try to take care of that issue too. Thanks for pointing that out.

**Comment by Julian** [comment]
Fixed in da4a6edc51e4927a1748685a5d11de868ad9a838 though as I said on the (closed) PR I hadn't noticed that @nomandhoni-cs it was you and not the PR author that had commented. Sorry! If I had, I firstly would have closed the PR and told that person this ticket was assigned, but certainly I would not have put in a fix myself. Have a look at my commit and see if you agree with it or have a suggestion. I also didn't address @harrel56's overflow, so maybe you can help fix that, or otherwise your help is of course appreciated on any ticket!
