### ISSUE TITLE
Don't center the commit information in the UI's run info

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#931]
We are centering the `Commit` information on [the homepage](https://bowtie.report) it seems:

![Screenshot 2024-02-24 at 9 46 32 AM](https://github.com/bowtie-json-schema/bowtie/assets/329822/775df754-83c4-4ee5-b896-133d46eb86c3)

but we should just treat that like all the other fields and have it left aligned.

**Comment by Akshaybagai52** [comment]
Hey @Julian Can I work on this issue ?

**Comment by Akshaybagai52** [comment]
> Go for it!

Thanks @Julian

**Comment by Akshaybagai52** [comment]
Hey @Julian this is the PR 
https://github.com/bowtie-json-schema/bowtie/pull/936
I've applied col-md-2 class with this mobile design remains unaffected 
let me know about your views
thanks

**Comment by Julian** [comment]
Fixed, well done!
