### ISSUE TITLE
Hide the implementation version column in the mobile UI

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#935]
For each implementation, we show a column containing its version. This is definitely useful information, as it tells a user what version of the library we're testing.

But it's definitely *less* useful than the actual test results.

On mobile right now, one sees:

![Screenshot 2024-02-24 at 9 55 24 PM](https://github.com/bowtie-json-schema/bowtie/assets/329822/5f3ba8d9-10d3-46c3-aecd-16171f91a438)

where a lot of horizontal space is taken up between the name and version columns. We should instead condense the table horizontally on mobile so that the version either collapses into the name column (if that's easy to do) or else not show it entirely.

**Comment by Sahil-Shadwal** [comment]
Hey I would like to work on this issue, can you please assign me.

**Comment by Swarnendu0123** [comment]
Hello @Julian, putting the tag inside the name column is a good choice. I can fix the issue, should I start working on this?
