### ISSUE TITLE
Instance copy button overflowing in Mobile mode

### ISSUE THREAD

**Issue by Swarnendu0123** [bowtie-json-schema/bowtie#943]
![IMG_20240226_113520.jpg](https://github.com/bowtie-json-schema/bowtie/assets/94161758/47a44fef-0f52-4dd4-8cf3-5dad27330894)

**Comment by Swarnendu0123** [comment]
Can I get this issue assigned?

**Comment by Julian** [comment]
Go for it, thanks.
