### ISSUE TITLE
Hover details does not have dark mode background color

### ISSUE THREAD

**Issue by JeelRajodiya** [bowtie-json-schema/bowtie#944]
## If you go to the summary table in the website and hover over a random test case. the text of the tool tip is not redable

![image](https://github.com/bowtie-json-schema/bowtie/assets/63534268/f6691815-4410-434e-b354-56d78cf4c6ee)
![image](https://github.com/bowtie-json-schema/bowtie/assets/63534268/7f190cbe-e188-44bd-a3c7-fa67a8a979a4)

## I like to create a PR for this issue, let me know @Julian

**Comment by Julian** [comment]
Sounds great, go for it!
