### ISSUE TITLE
border on instance column is removing from button

### ISSUE THREAD

**Issue by Akshaybagai52** [bowtie-json-schema/bowtie#954]
go to this url : https://bowtie.report/

and then open any accordion in mobile responsive after summary section then you can find that border bottom and top is removed from button as can be seen in image attached

![Screenshot 2024-02-27 at 10 33 25 AM](https://github.com/bowtie-json-schema/bowtie/assets/100753870/77f68b16-6bbe-4048-89b9-50fd2d6f9640)

I would like to work on this issue

**Comment by Swarnendu0123** [comment]
I guess it's due to padding, one of the solutions is to give equal column `col-6` to both and remove the `pe-4`

**Comment by Julian** [comment]
Sounds good!

**Comment by Akshaybagai52** [comment]
Hey @Julian can you review this 
mobile design :
![image](https://github.com/bowtie-json-schema/bowtie/assets/100753870/adcf88a1-73cc-4123-a142-1134759ee163)

desktop & tab :
![image](https://github.com/bowtie-json-schema/bowtie/assets/100753870/5ef5cd8f-b72a-473b-bb13-c60f9a431f8c)

Thanks

**Comment by Julian** [comment]
Oh, wait a minute, @Akshaybagai52 you have multiple things assigned to you -- please don't claim multiple things in progress, focus on one -- which do you want to work on, #954 + #964 to fix the schema/instance widget, or #947 for navbar padding?

**Comment by Julian** [comment]
Always send a PR when you have what you think is ready, there's no need to delay things and make it harder to review by hiding the code.

Also you probably meant to say "Whoops, I won't do that".

Anyways, your screenshot seems OK but the padding is inconsistent between the two copy icons, it's wider on the right in the Schema column and in the Instance column it's closer to the border. I'd make the instance column also have a bit of padding there.

**Comment by Akshaybagai52** [comment]
> Always send a PR when you have what you think is ready, there's no need to delay things and make it harder to review by hiding the code.
> 
> Also you probably meant to say "Whoops, I won't do that".
> 
> Anyways, your screenshot seems OK but the padding is inconsistent between the two copy icons, it's wider on the right in the Schema column and in the Instance column it's closer to the border. I'd make the instance column also have a bit of padding there.

Sorry for that It's just I want to confirm without raising PR, if you want then you can assign #947 to anyone who you want and I will complete #954 and #964

**Comment by ashmit-coder** [comment]
> > Always send a PR when you have what you think is ready, there's no need to delay things and make it harder to review by hiding the code.
> > Also you probably meant to say "Whoops, I won't do that".
> > Anyways, your screenshot seems OK but the padding is inconsistent between the two copy icons, it's wider on the right in the Schema column and in the Instance column it's closer to the border. I'd make the instance column also have a bit of padding there.
> 
> Sorry for that It's just I want to confirm without raising PR, if you want then you can assign #947 to anyone who you want and I will complete #954 and #964

Okay @Akshaybagai52  so i will work on #947 , if that's not an issue @Julian .

**Comment by Julian** [comment]
Great, go for it.

**Comment by Julian** [comment]
Fixed in #966.
