### ISSUE TITLE
Explicitly pass the released Bowtie version to the report workflow when we do a release

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#955]
There's a small race condition when regenerating reports just after a release -- namely the Install Bowtie step might install the previous version because it gets an old response from PyPI.

We should instead at least directly `==newversion` when we do the install, which will fail perhaps if the version still isn't downloadable from PyPI but at least will do so loudly.

**Comment by OptimumCode** [comment]
Hi @Julian. Do you mind if I take this one?

And just to make sure I correctly understand the problem: we need to pass the version when the report is triggered from [here](https://github.com/bowtie-json-schema/bowtie/blob/main/.github/workflows/ci.yml#L148), right? In all other cases we should use the latest available in PyPi version

And one question about:
> which will fail perhaps if the version still isn't downloadable from PyPI but at least will do so loudly

maybe we can try to repeat the installation in this case? And keep trying for 1 minute for example?

**Comment by OptimumCode** [comment]
I would add two parameters to bowtie action:

- specific version to install
- optional timeout to wait for the version to become available

**Comment by Julian** [comment]
> Hi @Julian. Do you mind if I take this one?

Not in the least, that would be super appreciated!

> And just to make sure I correctly understand the problem: we need to pass the version when the report is triggered from [here](https://github.com/bowtie-json-schema/bowtie/blob/main/.github/workflows/ci.yml#L148), right? In all other cases we should use the latest available in PyPi version

Exactly right yes! We just want to make sure if we just released, that we know there's a new version, so that one better be the one we install. In order to do that you'll have to also modify [our action file](https://github.com/bowtie-json-schema/bowtie/blob/main/action.yml) I think to take an input called `version`, which defaults to empty -- and then in places that use the action, like [here](https://github.com/bowtie-json-schema/bowtie/blob/7ca00a356b160cce46986dc8fa81a8de30ed2e5b/.github/workflows/report.yml#L66-L67) you then pass the one we just released. 

> maybe we can try to repeat the installation in this case? And keep trying for 1 minute for example?

If you can make that work without too much complexity that would be ideal! I think "wait for up to 1 minute for the install command to succeed should do it" yeah!

**Comment by OptimumCode** [comment]
@Julian, sorry for a maybe stupid question, but could you advise what is the best way to get the current version? If I got it right you use [hatch](https://hatch.pypa.io/latest/) to build distributions. And it has a `version` command that returns the current version. But I don't see that it installed is CI workflow so I am not sure if it is availabl (I haven't checked it yet...). Also there is a tag with version but I don't really want to parse the tag.
If the `hatch` is not available from the ci workflow what do you think about installing it along with `build` package?

**Comment by Julian** [comment]
> sorry for a maybe stupid question, but could you advise what is the best way to get the current version?

Not stupid at all! I think the easiest way is that GitHub actions has this in the triggering event info -- specifically the current version will be the `tag` for any event that was triggered by a release yes (which are the ones we're trying to modify the behavior of. Technically it will contain a `v` at the start but that shouldn't matter). In other words -- in short I think you don't need to touch Python for this, just GitHub actions things.

**Comment by OptimumCode** [comment]
> Technically it will contain a v at the start but that shouldn't matter

Do you mean there is no difference between `pipx install package==0.0.1` and `pipx install package==v0.0.1`?

Anyway, I will try to use tag for this then (trimming `v` if needed should not be a problem). Thank you for your suggestion

**Comment by Julian** [comment]
> Do you mean there is no difference between pipx install package==0.0.1 and pipx install package==v0.0.1?

Yes exactly right, the latter normalizes to the former according to Python packaging rules, though as you say you also can use some GHA str function if we really cared (we don't :D).

**Comment by Julian** [comment]
Actually I think you'll need to do minor string manipulation anyhow, because when the `version` isn't provided you want `pipx install bowtie` not `pipx install bowtie==`.

**Comment by OptimumCode** [comment]
Yep, I wanted to use 2 conditional steps: one with current installation (if version is empty) and one with `==version` (if version is not empty)

**Comment by Julian** [comment]
Makes sense, that should work too then.
