### ISSUE TITLE
Remove hardcoded paths / links to dialect reports

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#962]
A few places in the frontend hardcode paths to the reports for dialects, by doing e.g. `<NavLink to={`/dialects/${latest.shortName}`}>`.

Currently that seems to be:

```
frontend/src/components/OtherImplementations.tsx
64:                            <NavLink to={`/dialects/${latest.shortName}`}>

frontend/src/components/ImplementationReportView/DialectCompliance.tsx
61:                        href={`/dialects/${dialect.shortName}`}

frontend/src/components/NavBar.tsx
16:  const dialectsMatch = useMatch("/dialects/*");
84:                        to={`/dialects/${dialect.shortName}`}

```

There's no way that's the right way to do this link, there must be some notion of named routes in react ("link the user to the dialect page for this dialect"), which we should use instead of assuming that `/dialects/` is where that lives.

**Comment by matthewjselby** [comment]
I can take a look at this - it should be a good opportunity to familiarize myself with the codebase a bit more.

**Comment by Julian** [comment]
That'd be great! (Though this one will obviously familiarize you with the frontend moreso than the backend, but hopefully this shouldn't be too hard to knock off). Assigning you!

**Comment by matthewjselby** [comment]
As far as I can tell there actually isn't a notion of named routes in react router. I can add something that will emulate the functionality of something [like this](https://router.vuejs.org/guide/essentials/named-routes.html) by wrapping `NavLink`/`Link` from react router, but it will be a non-standard interface. For example:

```typescript
import { routeForName } from "../routes";
import { generatePath, NavLink } from "react-router-dom";

const NamedNavLink = (
    { 
        children,
        className = "",
        to
    }:
    { 
        children: string | JSX.Element | JSX.Element[] | (() => JSX.Element),
        className?: string,
        to: { name: string, params: object }
    }) => {
    const matchingRoute = routeForName(to.name);
    const path = generatePath(matchingRoute.path ?? "/", to.params);
    return (
        <NavLink className={className} to={path}>
            {children}
        </NavLink>
    );
};
```

with `routes.ts` being added to be the place where routes are defined, looking like:

```typescript
type NamedRoute = Partial<RouteObject> & { name: string };

export const routes: NamedRoute[] = [
    {
        name: "home",
        index: true,
        Component: ReportDataHandler,
        loader: reportDataLoader,
    },
    {
        name: "dialects",
        path: "/dialects/:draftName",
        Component: ReportDataHandler,
        loader: reportDataLoader,
    },
    {
        name: "local-report",
        path: "/local-report",
        Component: DragAndDrop,
    },
    {
        name: "implementations",
        path: "/implementations/:langImplementation",
        Component: ImplementationReportView,
        loader: async ({ params }) =>
            fetchAllReportData(params.langImplementation!),
    },
];

// Look for route with name, default to home if not found
export const routeForName: (name: string) => NamedRoute = (name: string) => {
    return (
        routes.find(route => route.name == name) ?? routes.find(route => route.name == "home")
    )!;
}
```

so the use would look like this:

```typescript
<NamedNavLink
  className="dropdown-item"
  to={
    {
      name: "dialects",
      params: {
        draftName: dialect.shortName
      }
    }
  }>
    {dialect.prettyName}
</NamedNavLink>
```

I have a working implementation, but I'm curious if you think this is a worthwhile addition for addressing this issue. If so I can submit a PR. Also open to other ideas if you have any.

**Comment by harrel56** [comment]
> Also CC @harrel56 just in case you know some of these answers offhand, I know you have some (a lot of?) react-router experience?

TBH I mainly used react-router in bowtie, so I wouldn't say that I have some significant experience - but I try my best :D 

A solution proposed by @matthewjselby seems really fine and it achieves what you want (kind of?) but IMO it's simply overengineered.

From my point of view hardcoding paths like this is perfectly fine - every other project that I worked on (different frameworks, routing libs) was using this approach. I feel like generally routing is only implemented to map uri -> page and not the other way around. But who knows, maybe there is some other approach that I'm not aware of.

**Comment by harrel56** [comment]
And just out of curiosity regarding compilation failures on paths:
```ts
export const routes = [
  {
    name: "home",
    index: true,
    Component: ReportDataHandler,
    loader: reportDataLoader,
  },
  {
    name: "dialects",
    path: "/dialects/:draftName",
    Component: ReportDataHandler,
    loader: reportDataLoader,
  },
  {
    name: "local-report",
    path: "/local-report",
    Component: DragAndDrop,
  },
  {
    name: "implementations",
    path: "/implementations/:langImplementation",
    Component: ImplementationReportView,
    loader: async ({ params }) =>
      fetchAllReportData(params.langImplementation!),
  },
] as const;

type ArrayElement<A> = A extends readonly (infer T)[] ? T : never
type RouteName = ArrayElement<typeof routes>['name']
const name: RouteName = 'home2' // fails with: Type 'home2' is not assignable to type 'home' | 'dialects' | 'local-report' |'implementations'
```
It turns out that you can extract a type which will only allow names that are defined in routes. I don't see a way in which path variables can be somehow validated by TS. OFC I'm not suggesting doing anything like this - it's more like fun fact how crazy you can go with TS

**Comment by matthewjselby** [comment]
> A solution proposed by @matthewjselby seems really fine and it achieves what you want (kind of?) but IMO it's simply overengineered.

Yeah that was my feeling, which is why I posted about it (far from a react expert myself).

> It turns out that you can extract a type which will only allow names that are defined in routes. I don't see a way in which path variables can be somehow validated by TS. OFC I'm not suggesting doing anything like this - it's more like fun fact how crazy you can go with TS

This is super cool! @harrel56 you say you don't suggest doing anything like this, can I ask why? It seems like a good way to validate and I assume will catch improper names (and could be adapted for other things) in linting, which would be convenient and accomplish the goals @Julian laid out above.

> the easiest solution is maybe to just have a function which returns a NavLink somewhere, and only use that to create them (e.g. `someDialect.report_link()` which returns a NavLink going to the `this` dialect's report).

I think this seems like a good solution that will accomplish the goals here (much less overengineered 😆) - I will run with this and report back. Maybe I can figure out how to validate path variables as @harrel56 mentioned above.

**Comment by harrel56** [comment]
> you say you don't suggest doing anything like this, can I ask why?

I mean if we decided that we go with the 1st approach (with names) then it wouldn't hurt, for sure :) but probably most of the people looking into code wouldn't know what's going on here (tbh I just copied `ArrayElement<T>` type definition from some SO thread and I don't know exactly what's happening there), so it's a some sort of maintenance cost, I guess? If something changes and these type needs to be rewritten then it can be problematic.
