### ISSUE TITLE
Schema/instance widgets are horizontal scrolling

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#964]
Our schema/instance component appears to be horizontally scrolling, both within dialect reports and also within test details modals:

https://github.com/bowtie-json-schema/bowtie/assets/329822/906c1d3f-f912-4f43-a327-966a77304ccf

**Comment by ashmit-coder** [comment]
Hey @Julian can i be assigned for this issue

**Comment by officeneerajsaini** [comment]
> Our schema/instance component appears to be horizontally scrolling, both within dialect reports and also within test details modals:
> 
>  Screen.Recording.2024-02-27.at.9.53.29.PM.mov

@Julian, can you provide some information about the expected behavior you want?

**Comment by nomandhoni-cs** [comment]
@officeneerajsaini, We don't want to a overflow horizontal scroll bar here. Also We want this to be responsive in all screen sizes
![image](https://github.com/bowtie-json-schema/bowtie/assets/92979541/bbd5bd28-3221-415f-ae36-7cf1ebcaec3a)

**Comment by ashmit-coder** [comment]
> @ashmit-coder, @officeneerajsaini, We don't want to a overflow horizontal scroll bar here. Also We want this to be responsive in all screen sizes
> 
> And Please wait for the issue to be assigned
> 
> ![image](https://private-user-images.githubusercontent.com/92979541/308491272-bbd5bd28-3221-415f-ae36-7cf1ebcaec3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTM0MjksIm5iZiI6MTcwOTExMzEyOSwicGF0aCI6Ii85Mjk3OTU0MS8zMDg0OTEyNzItYmJkNWJkMjgtMzIyMS00MTVmLWFlMzYtN2NmMWViY2FlYzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA5Mzg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNmQxNDcxYWViYWJmYTQ1YWU3NTczNjM2ZjgyMjVjNTEzOTBkY2VlZWFjYTQ3MjRlYzU0ZGE0MTkwZGE3MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ym6sXIOr9z87IT2ttNy1B_gC65XF17TZZ3tbdgvPITU)

Got the task @nomandhoni-cs  but will it be okay if i get started and make a PR?

**Comment by Julian** [comment]
We probably should combine this with #954 which @Akshaybagai52 is already working on, since the fix will possibly be the same, or at least touch the same few lines of code.

@Akshaybagai52 going to assign this one to you as well if that's ok.

@ashmit-coder let me know if you don't see anything else to pick up.

**Comment by Julian** [comment]
Fixed in #966.
