### ISSUE TITLE
icons are not centrally align and margin issue between two images

### ISSUE THREAD

**Issue by Akshaybagai52** [bowtie-json-schema/bowtie#971]
go to this url :- https://docs.bowtie.report/en/stable/
make it mobile responsive design and you can see that icons are not centrally align in this (dark mode & menu icon )
![Screenshot 2024-02-29 at 7 50 16 AM](https://github.com/bowtie-json-schema/bowtie/assets/100753870/cc222438-583f-4e40-9f3e-29ab55780761)

and now scroll down and you can see that there isn't any space between "open in github codespaces" and "open in gitpod"
![Screenshot 2024-02-29 at 7 51 17 AM](https://github.com/bowtie-json-schema/bowtie/assets/100753870/73af2767-26b4-48c5-981a-2a91de7d8944)

I would love to work on this issue

**Comment by Julian** [comment]
They're meant to be left aligned I guess, I don't think center aligned is appropriate there.

Though yeah in the second case a bit of space couldn't hurt if you want to play with Sphinx.

**Comment by Akshaybagai52** [comment]
Hey @Julian can you check this PR https://github.com/bowtie-json-schema/bowtie/pull/982
