### ISSUE TITLE
Misaligned heading in Mobile UI

### ISSUE THREAD

**Issue by Sahil-Shadwal** [bowtie-json-schema/bowtie#973]
![307677133-4a81085e-7d68-498f-b5f9-7720e639bcd4](https://github.com/bowtie-json-schema/bowtie/assets/119167601/79d59ebc-c869-45df-b88c-7cb353db0d30)

The error heading is misaligned in Mobile View . The "errors" heading is supposed to be a label for the first column, and et cetera.

**Comment by Sahil-Shadwal** [comment]
@Julian (Just mentioning you for reviewing). Thanks :)

**Comment by Julian** [comment]
This happens to be fixed as a byproduct of #1226 .
