### ISSUE TITLE
Edit button in docs website leads to 404 Page

### ISSUE THREAD

**Issue by ashmit-coder** [bowtie-json-schema/bowtie#979]
![Screenshot from 2024-03-02 03-02-26](https://github.com/bowtie-json-schema/bowtie/assets/69006513/89db7ffc-8f12-4b4f-bc01-5f2989115acb)

**Comment by Julian** [comment]
This was also reported [on Slack](https://json-schema.slack.com/archives/C0592558CBH/p1708964636798869?thread_ts=1708963778.297019&cid=C0592558CBH) I believe by @JeelRajodiya.

Certainly would be happy to see a fix, though see there, it may be in one of a few possible places, and only one of them is this repo.

**Comment by JeelRajodiya** [comment]
> This was also reported [on Slack](https://json-schema.slack.com/archives/C0592558CBH/p1708964636798869?thread_ts=1708963778.297019&cid=C0592558CBH) I believe by @JeelRajodiya.
> 
> Certainly would be happy to see a fix, though see there, it may be in one of a few possible places, and only one of them is this repo.

I tried to fix this, but when I build the docs locally there is no edit button. I am not sure how to debug this problem correctly

**Comment by Julian** [comment]
https://github.com/readthedocs/readthedocs.org/issues/1820 (which it seems was fixed by https://github.com/readthedocs/readthedocs.org/pull/6959 but clearly isn't working for us) is the relevant issue here. Let's see if someone upstream knows what's happening.
