### ISSUE TITLE
MetaMask plugin on Chrome weirdly tagging Bowtie Docs and Bowtie Report website as "potentially deceptive" 

### ISSUE THREAD

**Issue by adwait-godbole** [bowtie-json-schema/bowtie#980]
![Screenshot (58)](https://github.com/bowtie-json-schema/bowtie/assets/68469605/7acea2db-6e68-4cbf-8ad7-2c6cdd8db301)

Both Bowtie Docs website (https://docs.bowtie.report/en/stable/cli) and Bowtie Report website (https://bowtie.report/) are appearing to have been tagged as **potentially deceptive** by MetaMask chrome plugin. 

@Julian since you're the website owner likely this case should be logged on the below link for both the websites

https://github.com/MetaMask/eth-phishing-detect/issues

The logged cases on that repo already seem to be having a lot of "legitimate site blocked" cases for websites having ".report" as their _top level domains_.

**Comment by Julian** [comment]
Thanks for letting me know. That looks though like a cryptocurrency related extension, which is itself essentially malware as far as I'm concerned :) so I'm not very interested in engaging with it. If you use it (and insist on keeping it), perhaps see if they'll respond if you file it yourself, but yeah not interested I don't think in doing so myself.
