### ISSUE TITLE
Clipboard button on an empty instance copies `undefined`

### ISSUE THREAD

**Issue by SimonDMC** [bowtie-json-schema/bowtie#990]
Clicking the "Copy to clipboard" button on an empty instance copies the literal string `undefined`.

https://github.com/bowtie-json-schema/bowtie/assets/46278840/12dc236f-80cd-4b20-87bd-e6f56a1d3d62

I'd say the best way to fix this is to not render the Clipboard button at all whenever the instance is empty - it seems redundant in that case.

Happy to work on this once accepted.

**Comment by Julian** [comment]
> I'd say the best way to fix this is to not render the Clipboard button at all whenever the instance is empty - it seems redundant in that case.

I think an alternate fix which probably makes sense for other reasons might be to simply auto-select the first test when opened!

**Comment by Julian** [comment]
And yes feel free to grab this one, thanks for filing!
