### ISSUE TITLE
Add `bowtie filter-dialects` for filtering known dialects of JSON Schema

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#996]
As of #191 we now have `bowtie filter-implementations` for querying / filtering Bowtie's known implementations.

We should add `bowtie filter-dialects` for filtering known *JSON Schema dialects* and printing the URIs of those which match.

It should support:

* `bowtie filter-dialects --boolean-schemas / --no-boolean-schemas` for showing dialects which do or do not support boolean schemas
* `bowtie filter-dialects --latest` for showing the latest supported dialect

Output should always be in descending order of release date (i.e. newest dialect first).

**Comment by sudo-jarvis** [comment]
I can pick this one @Julian

**Comment by sudo-jarvis** [comment]
@Julian In this do we need to support something like: `bowtie filter-dialects -i python-jsonschema`, which would only show dialects which this implementation supports?
