### ISSUE TITLE
Deduplicate representation of implementations in the UI's report parsing

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#997]
The UI's representation of a parsed report has lots of duplication in it.

This is best seen by looking at the [one existing test](https://github.com/bowtie-json-schema/bowtie/blob/2fce2387436e673a9e9d83b24d8a9315e92d5f09/frontend/src/data/parseReportData.test.ts#L65-L125) for parsing reports, where you'll notice implementation metadata duplicated twice, including once mixed in with *counts* which are used for counting the number of tests with various outcomes.

We should remove this duplication, likely alongside also adding at least one or two more tests on the UI side as we try to increase the integration test coverage between the frontend and backend.

**Comment by Julian** [comment]
@adwait-godbole here you go

**Comment by adwait-godbole** [comment]
Thanks! I will start the work.

**Comment by adwait-godbole** [comment]
> also adding at least one or two more tests on the UI side as

for testing of which functionality exactly ?

**Comment by Julian** [comment]
The test there only runs a [single test case with one single test on one single dialect](https://github.com/bowtie-json-schema/bowtie/blob/2fce2387436e673a9e9d83b24d8a9315e92d5f09/frontend/src/data/parseReportData.test.ts#L55).

So -- one with more tests, test cases, a different dialect, and/or different combinations of test results is going to give more confidence that the code isn't just correct on a trivial example and broken on others.
